### ISSUE TITLE
shader compilation error

### ISSUE THREAD

**Issue by SupinePandora43** [HackerPoet/PySpace#15]
```
python ray_marcher_demo.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Compiling Vertex Shader...
Compiling Fragment Shader...
b'0(53) : error C1059: non constant expression in initialization\n'
Traceback (most recent call last):
  File "ray_marcher_demo.py", line 260, in <module>
    program = shader.compile(camera)
  File "C:\Games\Downloads\PySpace-master\pyspace\shader.py", line 73, in compile
    program = self.compile_program(v_shader, f_shader)
  File "C:\Games\Downloads\PySpace-master\pyspace\shader.py", line 106, in compile_program
    fragment_shader = self.compile_shader(fragment_source, GL_FRAGMENT_SHADER)
  File "C:\Games\Downloads\PySpace-master\pyspace\shader.py", line 92, in compile_shader
    raise ValueError('Shader compilation failed')
ValueError: Shader compilation failed
```

**Comment by nazarchek112** [comment]
You Just Maked It Wrong

**Comment by nazarchek112** [comment]
Here Is The File

**Comment by nazarchek112** [comment]
It Named Run Bat
